### ISSUE TITLE
Function definition is void: holiday-float

### ISSUE THREAD

**Issue by priyadarshan** [lawlist/lorg-calendar#1]
Hello,

Testing with no packages but lorg-calendar.el I get error:
```
Function definition is void: holiday-float
```
Emacs version:
`GNU Emacs 25.2.1 (amd64-portbld-freebsd11.0, GTK+ Version 3.22.15) of 2017-07-18`

Org version:
`Org-mode version 8.2.10 (release_8.2.10 @ /usr/local/share/emacs/25.2/lisp/org/)`

**Comment by lawlist** [comment]
`holiday-float` is defined in the library `holidays.el`.  If there is no `(require 'holidays)` at the outset of my code, then placing that snippet *at the outset* will fix the error.

**Comment by lawlist** [comment]
In the version that I use for daily workflow, I have made changes, improvements, bug-fixes, etc.  However, I have not updated the working draft that you are testing in a very long time.  That being said, the example should work out of the box and will give you an idea of how the concept was meant to work.

**Comment by priyadarshan** [comment]
Thank you, evaluating `(require 'holidays)` fixes the issue.

Would you consider sharing even a stripped down version of your latest code?

I find lorg-calendar offers exactly what I need and there is nothing close to it.

I would be happy to test if you wish (although I am sure there is no need).

Thank you very much for lorg-calendar and your help.

**Comment by lawlist** [comment]
:)  I would be pleased to update `lorg-calendar.el` in the coming days.  We can keep this issue open as a reminder, and I can let you know when the next draft is ready.  It will be based on Emacs 25, rather than a current release of org-mode that is now at 9.1 or something like that.

**Comment by priyadarshan** [comment]
Thank you, I will be happy to test.

I am using a few packages that requires the latest org-mode (9.1), but I could always setup a second Emacs instance, with its own separate emacs.d.

Thank you for considering this.

**Comment by priyadarshan** [comment]
If you are still available to share your latest code, I would still be eager to test it and use it :)

**Comment by lispstudent** [comment]
> If you are still available to share your latest code, I would still be eager to test it and use it :)

Same here.
