### ISSUE TITLE
Can it simply display calendar only?

### ISSUE THREAD

**Issue by basheewang** [lawlist/lorg-calendar#2]
Please don't generate an org file automatically.

**Comment by lawlist** [comment]
`foo.org` is a non-file-visiting-buffer for purposes of demonstrating how the library works.  The buffer will not be saved as a file unless the user manually saves it or has some type of automatic saving feature enabled for non-file-visiting-buffers.  A non-file-visiting-buffer, or a hard-coded file, would be needed to demonstrate these features.

**Comment by lawlist** [comment]
To see only the calendar without a demonstration of how to mark specific dates with tasks/events/holidays, see:  https://stackoverflow.com/questions/9547912/emacs-calendar-show-more-than-3-months/21409154#21409154

**Comment by lawlist** [comment]
> Please don't generate an org file automatically.

Excellent suggestion -- in hindsight 5 years later ... :)

The library has been updated to support a plain 12-month rotating calendar without sample events.

`M-x lawlist-year-calendar`

Thank you for the helpful comment / issue -- greatly appreciated!
