### ISSUE TITLE
missing autoload header?

### ISSUE THREAD

**Issue by danielkrajnik** [lawlist/lorg-calendar#4]
`lorg-calendar-generate` doesn't show up on the list of available commands - I've checked lorg-calendar.el and there are no `;;;###autoload` headers added?

If there is another way to load this library I would appreciate your advice.

**Comment by lawlist** [comment]
Subsequent to Emacs 26.3.50, there were a few changes to Emacs wherein `window--display-buffer` eliminated the fifth argument of DEDICATED and the alias `string-to-int` was eliminated.  Revisions in relation to those changes have been committed as of today (06/18/2023).

The `lorg-calendar` library contains a 12-month rotating calendar and an example of how to mark events on both the 3-month and 12-month calendars.  The main interactive function is `lorg-calendar-generate`, which can be used by typing `M-x lorg-calendar-generate`.   One idea would be to use `(require 'lorg-calendar)` in your `.emacs` or `init.el`, which contemplates that the `lorg-calendar.el` file be in the `load-path`.  If you would like to delay loading the library, then it would be possible to use the autoload statement above `lorg-calendar-generate` (which contemplates that the autoloads need to be regenerated after adding the `lorg-calendar` library).  If that works for your particular use-case and you find that helpful, then let me know and I can add that statement to the master.

**Comment by danielkrajnik** [comment]
Fantastic news, thank you for keep rocking this project 🎉

I'm on doom emacs so running `doom upgrade` updated the package from commit `4ab3222` to `1e5ed0f`. I always forget what equivalent of `require` is in doom, will check it in a moment.

**Comment by danielkrajnik** [comment]
Fantastic news, thank you for keep rocking this project 🎉

I'm on doom emacs so running `doom upgrade` updated the package from commit `4ab3222` to `1e5ed0f`.

> to use the autoload statement above lorg-calendar-generate

Yes, could we please add autoload above that function to the master? While straight.el package manager allows for adding changes locally I think it would be beneficial for others and have no negative effects for anyone not using a package manager? I now remember that `require` loads the package on each start which would slow down emacs start up times.

**Comment by lawlist** [comment]
The autoload statement has been added to `lorg-calendar-generate`.  Thank you for the helpful comments!
